### ISSUE TITLE
Simple replacer produces invalid JSON

### ISSUE THREAD

**Issue by erhhung** [JSON8/JSON8#18]
Here's a simple usage of a `replacer` function that aims to remove properties with an undefined value:

    > s = oo.serialize({foo: 'bar', baz: undefined}, {replacer: (k,v) => v})
    '{"foo":"bar",}'

    > JSON.parse(s)
    SyntaxError: Unexpected token }
        at Object.parse (native)

If the property removed is the last in the object, then the serialization leaves an extra comma.

**Comment by sonnyp** [comment]
thanks for the bug report

fixed in 0.8.2

**Comment by sonnyp** [comment]
@erhhung BTW, do you think a strict option on serialize method to enable/disable throwing for invalid JSON values would be useful? (strict: false would behave like JSON.stringify)

**Comment by erhhung** [comment]
Yes, I think that would be helpful. In offering essentially a replacement for the JSON module, you should, even if not the default behavior, an option to match the "baseline" behavior.

**Comment by erhhung** [comment]
If having `strict: false` would serialize an invalid value like `NaN` into `null`, it should also remove properties with undefined values like JSON.stringify(). Having to supply an **"identity"** `replacer` function like `(k, v) => v` offers no clue about why that would also remove undefined values--you're better off having an explicit option to remove undefined values so that other invalid values, which I treat in a different category than undefined, can still benefit from the default `strict: true` behavior.
