### ISSUE TITLE
How to serialize Map/Set if using a replacer?

### ISSUE THREAD

**Issue by erhhung** [JSON8/JSON8#19]
I'm trying to use a `replacer` function in order to remove properties with an undefined value. However, the object to serialize also contains new Map/Set structures, which aren't properly serialized if the replacer simply returns the value:

    > oo.serialize({foo: 'bar', baz: undefined, qux: new Map([['a', 1]])}, {replacer: (k,v) => v})
    '{"foo":"bar","qux":{}}'

I've tried to have the replacer return `oo(v)` or even `oo.serialize(v)` but the former doesn't work, and the latter complains about undefined values.

**Comment by sonnyp** [comment]
here is what I get

```
> oo.serialize({foo: 'bar', baz: undefined, qux: new Map([['a', 1]])}, {replacer: (k,v) => v})
'{"foo":"bar","qux":{"a":1}}'
```

looks like an issue with your node version, I'm using v5.3.0

**Comment by erhhung** [comment]
I'm on Node v5.0.0, but upgrading to v5.3.0 didn't help. I was using JSON8 v0.8.1, and after upgrading to v0.8.2 just now, I got the correct result, and it's the same, thankfully, in either Node version.

**Comment by sonnyp** [comment]
@erhhung ok good to know
