### ISSUE TITLE
JSON.stringify fixing

### ISSUE THREAD

**Issue by brettz9** [JSON8/JSON8#43]
You might want a fix like [this](https://github.com/linkedin/dustjs/issues/505#issue-44638469), or maybe [this](https://github.com/mapbox/safer-stringify/pull/1/files?diff=split) for [this problem](http://timelessrepo.com/json-isnt-a-javascript-subset)...

**Comment by sonnyp** [comment]
thanks,

https://github.com/JSON8/JSON8/pull/49

**Comment by sonnyp** [comment]
released as v0.9.2
