### ISSUE TITLE
oo.serialize(Map) hangs on large maps

### ISSUE THREAD

**Issue by kamil-maslowski** [JSON8/JSON8#47]
So I've been trying to use the serializer on node to serialize around 1500 elements in a Map, but for some reason serializer hangs, it works fine for smaller maps though.

The map contains user objects from github API (e.g https://developer.github.com/v3/repos/#list-contributors).

Are there any known bugs around that? Let me know if you need any debug details from me.

**Comment by sonnyp** [comment]
Can you copy paste an example of one of the map entry?

**Comment by kamil-maslowski** [comment]
Attaching 1811 elements (in fact link to all of them, cause github does not allow me to upload it :/) ;)
When I have a map with all of them serialize hangs, sorry for that much files, but didn't had any other option to do this.

[ALL FILE](http://www.megafileupload.com/7blx/output.zip)

And pasting one of the elements:

`{"login":"247GradLabs","id":19302650,"avatar_url":"https://avatars.githubusercontent.com/u/19302650?v=3","gravatar_id":"","url":"https://api.github.com/users/247GradLabs","html_url":"https://github.com/247GradLabs","followers_url":"https://api.github.com/users/247GradLabs/followers","following_url":"https://api.github.com/users/247GradLabs/following{/other_user}","gists_url":"https://api.github.com/users/247GradLabs/gists{/gist_id}","starred_url":"https://api.github.com/users/247GradLabs/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/247GradLabs/subscriptions","organizations_url":"https://api.github.com/users/247GradLabs/orgs","repos_url":"https://api.github.com/users/247GradLabs/repos","events_url":"https://api.github.com/users/247GradLabs/events{/privacy}","received_events_url":"https://api.github.com/users/247GradLabs/received_events","type":"User","site_admin":false,"contributions":1}`

**Comment by sonnyp** [comment]
so basically you have have an es6 Map with an entry for each file?

what options do you pass to json8.serialize?

**Comment by kamil-maslowski** [comment]
That is correct. I feel like it could be a problem with one of the entries, as when I have less of them everything is working fine - although hard to find out which one is breaking something.

No options passed to serialize, should there be any?

**Comment by sonnyp** [comment]
> No options passed to serialize, should there be any?

No.

> That is correct. I feel like it could be a problem with one of the entries, as when I have less of them everything is working fine - although hard to find out which one is breaking something.

You could serialize them one by one until you find an issue

**Comment by kamil-maslowski** [comment]
It's serializing all 1811 elements fine when done one by one, just tested.

Has to be a problem with large map.

**Comment by sonnyp** [comment]
Can you try with a plain object  {} instead of a map and JSON.stringify ?

**Comment by kamil-maslowski** [comment]
That went fine.

**Comment by sonnyp** [comment]
interesting, I'll give it a try

**Comment by kamil-maslowski** [comment]
Thanks!

fyi: I'm using 'login' as key

**Comment by sonnyp** [comment]
you mean the login of each user?

**Comment by sonnyp** [comment]
I made a test case and it works okay for me:

You'll need bluebird and the folder of the zip you passed me to be at `./output`

```javascript
'use strict'

const oo = require('json8')
const Promise = require('bluebird')
const fs = Promise.promisifyAll(require('fs'))
const path = require('path')

const map = new Map()

fs.readdirAsync('./output/')
  .then(filenames => {
    return Promise.each(filenames, filename => {
      const p = path.join('./output/', filename)
      return fs.readFileAsync(p, 'utf8').then(data => {
        const parsed = JSON.parse(data)
        // workaround file {"meta":{"x-ratelimit-limit":"5000","x-ratelimit-remaining":"4469","x-ratelimit-reset":"1468937816","status":"204 No Content"}}
        if (parsed.login !== undefined) {
          map.set(parsed.login, parsed)
        }
      })
    })
  })
  .then(() => {
    const s = oo.serialize(map)
    console.log(s)
  })
  .catch(err => {
    console.error(err)
  })
```

**Comment by sonnyp** [comment]
@kamil-maslowski were you able to fix your issue?

**Comment by kamil-maslowski** [comment]
@sonnyp didn't noticed your reply earlier.

Unfortunately at the moment I have a deadline on this week for something, so will test that around Sunday and let you know if that was something on my side (although the same issue occured on two computers).

Stay tuned ;)

**Comment by sonnyp** [comment]
@kamil-maslowski ok make sure to check out my previous reply

https://github.com/JSON8/JSON8/issues/47#issuecomment-233651859
