### ISSUE TITLE
Consider a pretty-print option that targets humans?

### ISSUE THREAD

**Issue by fasiha** [JSON8/JSON8#50]
This comes from the fact that JSON8 errors when `serialize`ing `Symbol`s. Even if these aren’t serializable in the technical sense, there’s value in displaying, for humans, that a particular value is a `Symbol`.

Thanks for considering!

**Comment by sonnyp** [comment]
Symbols aren't part of JSON so I'm not sure to see how it fits into JSON8

**Comment by fasiha** [comment]
Ah, I understand. My thinking was that, since JSON didn’t appear to support Map or Set either, JSON8 might eventually encompass things like Symbols too—and if this can’t be done properly because Symbols can’t be safely serialized/deserialized (the most important feature of JSON), then perhaps JSON8 could have a “pseudo-serializer” or pretty-printer supporting these ES6 types—perhaps becoming a standardized version of `console.log`. But with a bit more sleep, I agree that this seems really out of scope for JSON8 so I’ll close this thread. Sorry to bug you!
